## This Python 3 environment comes with many helpful analytics libraries installed
## It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
## For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Input data files are available in the "../input/" directory.
## For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Import data
train = pd.DataFrame(pd.read_csv('../input/train.csv'))
test = pd.DataFrame(pd.read_csv('../input/test.csv'))

In [141]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [142]:
# Import data
train = pd.DataFrame(pd.read_csv('train.csv'))
test = pd.DataFrame(pd.read_csv('test.csv'))

In [143]:
train.head()

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq,Target
0,ID_279628684,190000.0,0,3,0,1,1,0,NaN,0,...,100,1849,1,100,0,1.000000,0.0,100.0,1849,4
1,ID_f29eb3ddd,135000.0,0,4,0,1,1,1,1.0,0,...,144,4489,1,144,0,1.000000,64.0,144.0,4489,4
2,ID_68de51c94,NaN,0,8,0,1,1,0,NaN,0,...,121,8464,1,0,0,0.250000,64.0,121.0,8464,4
3,ID_d671db89c,180000.0,0,5,0,1,1,1,1.0,0,...,81,289,16,121,4,1.777778,1.0,121.0,289,4
4,ID_d56d6f5f5,180000.0,0,5,0,1,1,1,1.0,0,...,121,1369,16,121,4,1.777778,1.0,121.0,1369,4

In [144]:
prac = train.copy()

In [145]:
prac.describe()

,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,r4h2,...,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq,Target
count,2.697000e+03,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,2215.000000,9557.000000,9557.000000,...,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9552.000000,9557.000000,9557.000000
mean,1.652316e+05,0.038087,4.955530,0.023648,0.994768,0.957623,0.231767,1.404063,0.385895,1.559171,...,74.222769,1643.774302,19.132887,53.500262,3.844826,3.249485,3.900409,102.588867,1643.774302,3.302292
std,1.504571e+05,0.191417,1.468381,0.151957,0.072145,0.201459,0.421983,0.763131,0.680779,1.036574,...,76.777549,1741.197050,18.751395,78.445804,6.946296,4.129547,12.511831,93.516890,1741.197050,1.009565
min,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.040000,0.000000,0.000000,0.000000,1.000000
25%,8.000000e+04,0.000000,4.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,16.000000,289.000000,9.000000,0.000000,0.000000,1.000000,0.111111,36.000000,289.000000,3.000000
50%,1.300000e+05,0.000000,5.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,36.000000,961.000000,16.000000,36.000000,1.000000,2.250000,0.444444,81.000000,961.000000,4.000000
75%,2.000000e+05,0.000000,6.000000,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000,2.000000,...,121.000000,2601.000000,25.000000,81.000000,4.000000,4.000000,1.777778,134.560010,2601.000000,4.000000
max,2.353477e+06,1.000000,11.000000,1.000000,1.000000,1.000000,1.000000,6.000000,5.000000,8.000000,...,441.000000,9409.000000,169.000000,441.000000,81.000000,36.000000,64.000000,1369.000000,9409.000000,4.000000

In [146]:
prac.drop(['SQBescolari', 'SQBage', 'SQBhogar_total', 'SQBedjefe', 'SQBhogar_nin', 'SQBovercrowding', 
          'SQBdependency', 'SQBmeaned', 'agesq'], axis=1, inplace=True)
prac.describe()

,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,r4h2,...,lugar1,lugar2,lugar3,lugar4,lugar5,lugar6,area1,area2,age,Target
count,2.697000e+03,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,2215.000000,9557.000000,9557.000000,...,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000
mean,1.652316e+05,0.038087,4.955530,0.023648,0.994768,0.957623,0.231767,1.404063,0.385895,1.559171,...,0.587632,0.092707,0.062363,0.082767,0.093858,0.080674,0.714555,0.285445,34.303547,3.302292
std,1.504571e+05,0.191417,1.468381,0.151957,0.072145,0.201459,0.421983,0.763131,0.680779,1.036574,...,0.492286,0.290036,0.241826,0.275543,0.291646,0.272348,0.451650,0.451650,21.612261,1.009565
min,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,8.000000e+04,0.000000,4.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.000000,3.000000
50%,1.300000e+05,0.000000,5.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,31.000000,4.000000
75%,2.000000e+05,0.000000,6.000000,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000,2.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,51.000000,4.000000
max,2.353477e+06,1.000000,11.000000,1.000000,1.000000,1.000000,1.000000,6.000000,5.000000,8.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,97.000000,4.000000

In [147]:
group = prac.groupby('idhogar', as_index=False).sum()
group[['idhogar', 'rooms']].head()
group[group['idhogar'] == '2b58d945f']

,idhogar,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,lugar1,lugar2,lugar3,lugar4,lugar5,lugar6,area1,area2,age,Target
513,2b58d945f,720000.0,0,20,0,4,4,4,4.0,0,...,4,0,0,0,0,0,4,0,100,16

In [148]:
train.stack()

0     Id                 ID_279628684
      v2a1                     190000
      hacdor                        0
      rooms                         3
      hacapo                        0
      v14a                          1
      refrig                        1
      v18q                          0
      r4h1                          0
      r4h2                          1
      r4h3                          1
      r4m1                          0
      r4m2                          0
      r4m3                          0
      r4t1                          0
      r4t2                          1
      r4t3                          1
      tamhog                        1
      tamviv                        1
      escolari                     10
      hhsize                        1
      paredblolad                   1
      paredzocalo                   0
      paredpreb                     0
      pareddes                      0
      paredmad                      0
      paredzinc                     0
      paredfibras                   0
      paredother                    0
      pisomoscer                    1
                             ...
9556  bedrooms                      4
      overcrowding               1.25
      tipovivi1                     0
      tipovivi2                     0
      tipovivi3                     1
      tipovivi4                     0
      tipovivi5                     0
      computer                      0
      television                    1
      mobilephone                   1
      qmobilephone                  3
      lugar1                        0
      lugar2                        0
      lugar3                        0
      lugar4                        0
      lugar5                        0
      lugar6                        1
      area1                         0
      area2                         1
      age                          21
      SQBescolari                  64
      SQBage                      441
      SQBhogar_total               25
      SQBedjefe                    81
      SQBhogar_nin                  1
      SQBovercrowding          1.5625
      SQBdependency            0.0625
      SQBmeaned               68.0625
      agesq                       441
      Target                        2
Length: 1344511, dtype: object

In [149]:
train.describe()

,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,r4h2,...,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq,Target
count,2.697000e+03,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,2215.000000,9557.000000,9557.000000,...,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9557.000000,9552.000000,9557.000000,9557.000000
mean,1.652316e+05,0.038087,4.955530,0.023648,0.994768,0.957623,0.231767,1.404063,0.385895,1.559171,...,74.222769,1643.774302,19.132887,53.500262,3.844826,3.249485,3.900409,102.588867,1643.774302,3.302292
std,1.504571e+05,0.191417,1.468381,0.151957,0.072145,0.201459,0.421983,0.763131,0.680779,1.036574,...,76.777549,1741.197050,18.751395,78.445804,6.946296,4.129547,12.511831,93.516890,1741.197050,1.009565
min,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.040000,0.000000,0.000000,0.000000,1.000000
25%,8.000000e+04,0.000000,4.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,16.000000,289.000000,9.000000,0.000000,0.000000,1.000000,0.111111,36.000000,289.000000,3.000000
50%,1.300000e+05,0.000000,5.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,36.000000,961.000000,16.000000,36.000000,1.000000,2.250000,0.444444,81.000000,961.000000,4.000000
75%,2.000000e+05,0.000000,6.000000,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000,2.000000,...,121.000000,2601.000000,25.000000,81.000000,4.000000,4.000000,1.777778,134.560010,2601.000000,4.000000
max,2.353477e+06,1.000000,11.000000,1.000000,1.000000,1.000000,1.000000,6.000000,5.000000,8.000000,...,441.000000,9409.000000,169.000000,441.000000,81.000000,36.000000,64.000000,1369.000000,9409.000000,4.000000

In [150]:
train.dtypes.value_counts()

int64      130
float64      8
object       5
dtype: int64

Most of the columns are float/int, but there are 5 object columns that need to be dealt with/dropped

In [151]:
train.columns[train.dtypes == object]

Index(['Id', 'idhogar', 'dependency', 'edjefe', 'edjefa'], dtype='object')

Id and idhogar are unique identifiers.  Looking at the remaining 3 object columns:

In [152]:
train['dependency'].unique()

array(['no', '8', 'yes', '3', '.5', '.25', '2', '.66666669', '.33333334',
       '1.5', '.40000001', '.75', '1.25', '.2', '2.5', '1.2', '4',
       '1.3333334', '2.25', '.22222222', '5', '.83333331', '.80000001',
       '6', '3.5', '1.6666666', '.2857143', '1.75', '.71428573',
       '.16666667', '.60000002'], dtype=object)

Since we have a dependency squared column and a edjefe squared column, we can easily take the square root of that as a fix.

In [153]:
train[['dependency', 'SQBdependency', 'edjefe', 'SQBedjefe']].head()

  dependency  SQBdependency edjefe  SQBedjefe
0         no            0.0     10        100
1          8           64.0     12        144
2          8           64.0     no          0
3        yes            1.0     11        121
4        yes            1.0     11        121

In [154]:
train['dependency'] = np.sqrt(train['SQBdependency'])
train['edjefe'] = np.sqrt(train['SQBedjefe'])

**edjefa:** *years of education of female head of household, based on the interaction of escolari (years of education), head of household and gender, yes=1 and no=0*

So we can just change 'no' to 0 and 'yes' to 1

In [155]:
for col in train.columns:
   train.loc[train['edjefa'] == 'no', col] = 0
   train.loc[train['edjefa'] == 'yes', col] = 1
    
train['edjefa'] = train['edjefa'].astype('int64')
train['edjefa'].head()

0     0
1     0
2    11
3     0
4     0
Name: edjefa, dtype: int64

In [156]:
## Make sure everything worked well
train.dtypes.value_counts()

int64      131
float64     10
object       2
dtype: int64

Now to deal with null values.

In [157]:
train.columns[train.isnull().sum() !=0]

Index(['v2a1', 'v18q1', 'rez_esc', 'meaneduc', 'SQBmeaned'], dtype='object')

**v2a1:** Monthly rent payment

**v18q1:** number of tablets household owns

**rez_esc:** Years behind in school

**meaneduc:** Average years of education for adults (18+)

**SQBmeaned:** Square of the mean years of education of adults (>=18) in the household

In [158]:
train[['v2a1', 'v18q1', 'rez_esc', 'meaneduc', 'SQBmeaned']].isnull().sum()

v2a1         2336
v18q1        2544
rez_esc      2667
meaneduc        5
SQBmeaned       5
dtype: int64

For 'meaneduc' and 'SQBmeaned', null values can be replaced with 0 as they represent the mean years of education of adults (>=18) in the household.

In [159]:
train[train['meaneduc'].isnull()][['meaneduc', 'SQBmeaned']]

      meaneduc  SQBmeaned
1291       NaN        NaN
1840       NaN        NaN
1841       NaN        NaN
2049       NaN        NaN
2050       NaN        NaN

In [160]:
train['meaneduc'] = train['meaneduc'].fillna(0)
train['SQBmeaned'] = train['SQBmeaned'].fillna(0)

Since the 'v18q1' column is null if 'v18q' (owns a tablet) is false, we can replace null values with 0.

In [161]:
train[train['v18q1'].isnull()][['v18q1', 'v18q']].head()

    v18q1  v18q
2     NaN     0
11    NaN     0
12    NaN     0
15    NaN     0
16    NaN     0

In [162]:
train['v18q1'] = train['v18q1'].fillna(0)

For years behind in school ('rez_esc'), it might be possible to fill null values by examining children in the house since these values probably mean 0 years behind.

In [163]:
train[(train['rez_esc'].isnull() == True) & (train['age'] < 18) & (train['escolari'] > 0)].head()

Empty DataFrame
Columns: [Id, v2a1, hacdor, rooms, hacapo, v14a, refrig, v18q, v18q1, r4h1, r4h2, r4h3, r4m1, r4m2, r4m3, r4t1, r4t2, r4t3, tamhog, tamviv, escolari, rez_esc, hhsize, paredblolad, paredzocalo, paredpreb, pareddes, paredmad, paredzinc, paredfibras, paredother, pisomoscer, pisocemento, pisoother, pisonatur, pisonotiene, pisomadera, techozinc, techoentrepiso, techocane, techootro, cielorazo, abastaguadentro, abastaguafuera, abastaguano, public, planpri, noelec, coopele, sanitario1, sanitario2, sanitario3, sanitario5, sanitario6, energcocinar1, energcocinar2, energcocinar3, energcocinar4, elimbasu1, elimbasu2, elimbasu3, elimbasu4, elimbasu5, elimbasu6, epared1, epared2, epared3, etecho1, etecho2, etecho3, eviv1, eviv2, eviv3, dis, male, female, estadocivil1, estadocivil2, estadocivil3, estadocivil4, estadocivil5, estadocivil6, estadocivil7, parentesco1, parentesco2, parentesco3, parentesco4, parentesco5, parentesco6, parentesco7, parentesco8, parentesco9, parentesco10, parentesco11, parentesco12, idhogar, hogar_nin, hogar_adul, hogar_mayor, hogar_total, ...]
Index: []

[0 rows x 143 columns]

Since the null values are either children or adults that aren't behind in school, we can replace them with 0

In [164]:
train['rez_esc'] = train['rez_esc'].fillna(0)

For monthly rent payment 'v2a1', it makes sense to look at if they own the home, rent, homeless, etc.  It looks like null values can be filled with 0 since these people either own the house fully or are in a precarious living situation.

In [165]:
train['v2a1'] = train['v2a1'].fillna(0)

In [166]:
train[train['idhogar']=='4b6077882'][['idhogar', 'parentesco1', 'Target']]

       idhogar  parentesco1  Target
282  4b6077882            1       1
283  4b6077882            0       2
284  4b6077882            0       2

In [167]:
df = train[train['parentesco1'] == 1]
d = pd.Series(df['Target'].values, index=df['idhogar']).to_dict()
train.set_index('idhogar', inplace=True)
train['Target'].update(pd.Series(d))
train.reset_index(inplace=True)

In [168]:
train[train['idhogar']=='4b6077882'][['idhogar', 'parentesco1', 'Target']]

       idhogar  parentesco1  Target
282  4b6077882            1       1
283  4b6077882            0       1
284  4b6077882            0       1

In [169]:
# Function to use on test data

def clean_data(data):
    # Dealing with objects in dataframe
    data['dependency'] = np.sqrt(data['SQBdependency'])
    data['edjefe'] = np.sqrt(data['SQBedjefe'])
    for col in data.columns:
        data.loc[data['edjefa'] == 'no', col] = 0
        data.loc[data['edjefa'] == 'yes', col] = 1
    data['edjefa'] = data['edjefa'].astype('int64')
    
    # Dealing with null values
    data['meaneduc'] = data['meaneduc'].fillna(0)
    data['SQBmeaned'] = data['SQBmeaned'].fillna(0)
    data['v18q1'] = data['v18q1'].fillna(0)
    data['rez_esc'] = data['rez_esc'].fillna(0)
    data['v2a1'] = data['v2a1'].fillna(0)
    
    return data

In [170]:
test = clean_data(test)
test_set = test.copy()
test_set.set_index('Id', inplace=True)
test_set.drop('idhogar', axis=1, inplace=True)

I'll use a LightGBM model to make predictions on the test set.  I've also left in all of the features, but the model could likely be improved by dropping some of them.

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from lightgbm import LGBMClassifier as lgb

In [131]:
X = train.drop(['Id', 'idhogar', 'Target'], axis = 1)
y = train['Target']
#X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=101)

In [132]:
model = lgb(boosting_type='dart', class_weight='balanced', n_estimators=350, learning_rate=0.3, 
             max_depth=10, importance_type='gain', colsample_bytree=1, random_state=101)

In [133]:
kf = StratifiedKFold(n_splits=5, shuffle=True)

In [171]:
predicts = []
for train_index, test_index in kf.split(X, y):
    print("###")
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], 
            early_stopping_rounds=20)
    predicts.append(model.predict(test_set))

###
[1]	valid_0's multi_logloss: 1.22998
Training until validation scores don't improve for 20 rounds.
[2]	valid_0's multi_logloss: 1.12542
[3]	valid_0's multi_logloss: 1.05577
[4]	valid_0's multi_logloss: 0.995812
[5]	valid_0's multi_logloss: 0.946006
[6]	valid_0's multi_logloss: 0.909777
[7]	valid_0's multi_logloss: 0.876247
[8]	valid_0's multi_logloss: 0.849674
[9]	valid_0's multi_logloss: 0.825457
[10]	valid_0's multi_logloss: 0.835645
[11]	valid_0's multi_logloss: 0.815545
[12]	valid_0's multi_logloss: 0.793986
[13]	valid_0's multi_logloss: 0.778686
[14]	valid_0's multi_logloss: 0.762688
[15]	valid_0's multi_logloss: 0.770315
[16]	valid_0's multi_logloss: 0.756534
[17]	valid_0's multi_logloss: 0.756278
[18]	valid_0's multi_logloss: 0.754206
[19]	valid_0's multi_logloss: 0.739085
[20]	valid_0's multi_logloss: 0.72351
[21]	valid_0's multi_logloss: 0.710378
[22]	valid_0's multi_logloss: 0.712453
[23]	valid_0's multi_logloss: 0.714565
[24]	valid_0's multi_logloss: 0.701302
[25]	valid_0's multi_logloss: 0.694201
[26]	valid_0's multi_logloss: 0.682244
[27]	valid_0's multi_logloss: 0.683358
[28]	valid_0's multi_logloss: 0.689604
[29]	valid_0's multi_logloss: 0.678213
[30]	valid_0's multi_logloss: 0.665155
[31]	valid_0's multi_logloss: 0.667068
[32]	valid_0's multi_logloss: 0.653829
[33]	valid_0's multi_logloss: 0.646119
[34]	valid_0's multi_logloss: 0.638024
[35]	valid_0's multi_logloss: 0.640216
[36]	valid_0's multi_logloss: 0.643075
[37]	valid_0's multi_logloss: 0.648638
[38]	valid_0's multi_logloss: 0.653321
[39]	valid_0's multi_logloss: 0.64185
[40]	valid_0's multi_logloss: 0.645089
[41]	valid_0's multi_logloss: 0.649343
[42]	valid_0's multi_logloss: 0.652206
[43]	valid_0's multi_logloss: 0.653139
[44]	valid_0's multi_logloss: 0.657568
[45]	valid_0's multi_logloss: 0.646967
[46]	valid_0's multi_logloss: 0.648932
[47]	valid_0's multi_logloss: 0.652955
[48]	valid_0's multi_logloss: 0.654945
[49]	valid_0's multi_logloss: 0.659272
[50]	valid_0's multi_logloss: 0.664164
[51]	valid_0's multi_logloss: 0.653067
[52]	valid_0's multi_logloss: 0.642456
[53]	valid_0's multi_logloss: 0.64504
[54]	valid_0's multi_logloss: 0.636524
[55]	valid_0's multi_logloss: 0.638024
[56]	valid_0's multi_logloss: 0.641653
[57]	valid_0's multi_logloss: 0.630606
[58]	valid_0's multi_logloss: 0.635105
[59]	valid_0's multi_logloss: 0.626406
[60]	valid_0's multi_logloss: 0.62691
[61]	valid_0's multi_logloss: 0.631525
[62]	valid_0's multi_logloss: 0.622967
[63]	valid_0's multi_logloss: 0.615078
[64]	valid_0's multi_logloss: 0.609083
[65]	valid_0's multi_logloss: 0.601926
[66]	valid_0's multi_logloss: 0.596312
[67]	valid_0's multi_logloss: 0.597093
[68]	valid_0's multi_logloss: 0.597346
[69]	valid_0's multi_logloss: 0.592031
[70]	valid_0's multi_logloss: 0.594943
[71]	valid_0's multi_logloss: 0.584249
[72]	valid_0's multi_logloss: 0.578657
[73]	valid_0's multi_logloss: 0.574654
[74]	valid_0's multi_logloss: 0.57816
[75]	valid_0's multi_logloss: 0.582135
[76]	valid_0's multi_logloss: 0.575227
[77]	valid_0's multi_logloss: 0.577856
[78]	valid_0's multi_logloss: 0.570515
[79]	valid_0's multi_logloss: 0.572709
[80]	valid_0's multi_logloss: 0.574848
[81]	valid_0's multi_logloss: 0.568091
[82]	valid_0's multi_logloss: 0.561935
[83]	valid_0's multi_logloss: 0.564236
[84]	valid_0's multi_logloss: 0.557802
[85]	valid_0's multi_logloss: 0.559045
[86]	valid_0's multi_logloss: 0.56209
[87]	valid_0's multi_logloss: 0.557714
[88]	valid_0's multi_logloss: 0.560323
[89]	valid_0's multi_logloss: 0.551972
[90]	valid_0's multi_logloss: 0.5451
[91]	valid_0's multi_logloss: 0.540261
[92]	valid_0's multi_logloss: 0.542653
[93]	valid_0's multi_logloss: 0.544351
[94]	valid_0's multi_logloss: 0.547486
[95]	valid_0's multi_logloss: 0.549575
[96]	valid_0's multi_logloss: 0.542038
[97]	valid_0's multi_logloss: 0.534097
[98]	valid_0's multi_logloss: 0.530232
[99]	valid_0's multi_logloss: 0.532689
[100]	valid_0's multi_logloss: 0.525158
[101]	valid_0's multi_logloss: 0.526309
[102]	valid_0's multi_logloss: 0.528952
[103]	valid_0's multi_logloss: 0.524791
[104]	valid_0's multi_logloss: 0.526966
[105]	valid_0's multi_logloss: 0.520978
[106]	valid_0's multi_logloss: 0.515559
[107]	valid_0's multi_logloss: 0.509853
[108]	valid_0's multi_logloss: 0.512441
[109]	valid_0's multi_logloss: 0.514129
[110]	valid_0's multi_logloss: 0.517087
[111]	valid_0's multi_logloss: 0.510006
[112]	valid_0's multi_logloss: 0.504873
[113]	valid_0's multi_logloss: 0.500177
[114]	valid_0's multi_logloss: 0.50232
[115]	valid_0's multi_logloss: 0.498043
[116]	valid_0's multi_logloss: 0.50012
[117]	valid_0's multi_logloss: 0.502079
[118]	valid_0's multi_logloss: 0.50439
[119]	valid_0's multi_logloss: 0.500782
[120]	valid_0's multi_logloss: 0.503164
[121]	valid_0's multi_logloss: 0.496417
[122]	valid_0's multi_logloss: 0.492405
[123]	valid_0's multi_logloss: 0.490389
[124]	valid_0's multi_logloss: 0.484817
[125]	valid_0's multi_logloss: 0.486931
[126]	valid_0's multi_logloss: 0.488594
[127]	valid_0's multi_logloss: 0.483645
[128]	valid_0's multi_logloss: 0.478774
[129]	valid_0's multi_logloss: 0.472975
[130]	valid_0's multi_logloss: 0.466101
[131]	valid_0's multi_logloss: 0.459794
[132]	valid_0's multi_logloss: 0.460964
[133]	valid_0's multi_logloss: 0.45724
[134]	valid_0's multi_logloss: 0.451939
[135]	valid_0's multi_logloss: 0.447736
[136]	valid_0's multi_logloss: 0.44515
[137]	valid_0's multi_logloss: 0.442513
[138]	valid_0's multi_logloss: 0.440783
[139]	valid_0's multi_logloss: 0.442694
[140]	valid_0's multi_logloss: 0.44416
[141]	valid_0's multi_logloss: 0.440372
[142]	valid_0's multi_logloss: 0.442044
[143]	valid_0's multi_logloss: 0.43715
[144]	valid_0's multi_logloss: 0.43886
[145]	valid_0's multi_logloss: 0.440726
[146]	valid_0's multi_logloss: 0.43582
[147]	valid_0's multi_logloss: 0.433345
[148]	valid_0's multi_logloss: 0.430239
[149]	valid_0's multi_logloss: 0.431482
[150]	valid_0's multi_logloss: 0.432705
[151]	valid_0's multi_logloss: 0.434505
[152]	valid_0's multi_logloss: 0.429878
[153]	valid_0's multi_logloss: 0.431638
[154]	valid_0's multi_logloss: 0.427076
[155]	valid_0's multi_logloss: 0.424307
[156]	valid_0's multi_logloss: 0.420317
[157]	valid_0's multi_logloss: 0.421929
[158]	valid_0's multi_logloss: 0.419475
[159]	valid_0's multi_logloss: 0.416868
[160]	valid_0's multi_logloss: 0.415255
[161]	valid_0's multi_logloss: 0.41697
[162]	valid_0's multi_logloss: 0.414184
[163]	valid_0's multi_logloss: 0.411312
[164]	valid_0's multi_logloss: 0.408831
[165]	valid_0's multi_logloss: 0.409804
[166]	valid_0's multi_logloss: 0.406239
[167]	valid_0's multi_logloss: 0.407843
[168]	valid_0's multi_logloss: 0.409409
[169]	valid_0's multi_logloss: 0.410881
[170]	valid_0's multi_logloss: 0.412285
[171]	valid_0's multi_logloss: 0.41393
[172]	valid_0's multi_logloss: 0.412718
[173]	valid_0's multi_logloss: 0.414006
[174]	valid_0's multi_logloss: 0.410075
[175]	valid_0's multi_logloss: 0.405205
[176]	valid_0's multi_logloss: 0.403703
[177]	valid_0's multi_logloss: 0.400063
[178]	valid_0's multi_logloss: 0.397646
[179]	valid_0's multi_logloss: 0.398936
[180]	valid_0's multi_logloss: 0.400457
[181]	valid_0's multi_logloss: 0.398934
[182]	valid_0's multi_logloss: 0.400436
[183]	valid_0's multi_logloss: 0.401476
[184]	valid_0's multi_logloss: 0.397196
[185]	valid_0's multi_logloss: 0.398565
[186]	valid_0's multi_logloss: 0.399879
[187]	valid_0's multi_logloss: 0.401405
[188]	valid_0's multi_logloss: 0.397908
[189]	valid_0's multi_logloss: 0.39475
[190]	valid_0's multi_logloss: 0.392662
[191]	valid_0's multi_logloss: 0.390035
[192]	valid_0's multi_logloss: 0.391446
[193]	valid_0's multi_logloss: 0.38827
[194]	valid_0's multi_logloss: 0.389325
[195]	valid_0's multi_logloss: 0.3903
[196]	valid_0's multi_logloss: 0.391413
[197]	valid_0's multi_logloss: 0.393063
[198]	valid_0's multi_logloss: 0.394413
[199]	valid_0's multi_logloss: 0.395804
[200]	valid_0's multi_logloss: 0.396722
[201]	valid_0's multi_logloss: 0.393736
[202]	valid_0's multi_logloss: 0.391735
[203]	valid_0's multi_logloss: 0.393362
[204]	valid_0's multi_logloss: 0.390554
[205]	valid_0's multi_logloss: 0.388139
[206]	valid_0's multi_logloss: 0.389247
[207]	valid_0's multi_logloss: 0.390456
[208]	valid_0's multi_logloss: 0.386924

[209]	valid_0's multi_logloss: 0.387857
[210]	valid_0's multi_logloss: 0.388907
[211]	valid_0's multi_logloss: 0.387357
[212]	valid_0's multi_logloss: 0.388687
[213]	valid_0's multi_logloss: 0.389706
[214]	valid_0's multi_logloss: 0.390808
[215]	valid_0's multi_logloss: 0.391909
[216]	valid_0's multi_logloss: 0.393117
[217]	valid_0's multi_logloss: 0.390708
[218]	valid_0's multi_logloss: 0.388976
[219]	valid_0's multi_logloss: 0.39022
[220]	valid_0's multi_logloss: 0.391445
[221]	valid_0's multi_logloss: 0.392877
[222]	valid_0's multi_logloss: 0.39062
[223]	valid_0's multi_logloss: 0.391561
[224]	valid_0's multi_logloss: 0.392587
[225]	valid_0's multi_logloss: 0.388933
[226]	valid_0's multi_logloss: 0.386504
[227]	valid_0's multi_logloss: 0.387889
[228]	valid_0's multi_logloss: 0.388987
[229]	valid_0's multi_logloss: 0.387944
[230]	valid_0's multi_logloss: 0.389236
[231]	valid_0's multi_logloss: 0.384927
[232]	valid_0's multi_logloss: 0.382049
[233]	valid_0's multi_logloss: 0.379551
[234]	valid_0's multi_logloss: 0.38059
[235]	valid_0's multi_logloss: 0.377658
[236]	valid_0's multi_logloss: 0.375923
[237]	valid_0's multi_logloss: 0.374463
[238]	valid_0's multi_logloss: 0.375539
[239]	valid_0's multi_logloss: 0.372096
[240]	valid_0's multi_logloss: 0.373037
[241]	valid_0's multi_logloss: 0.374056
[242]	valid_0's multi_logloss: 0.37211
[243]	valid_0's multi_logloss: 0.370141
[244]	valid_0's multi_logloss: 0.37112
[245]	valid_0's multi_logloss: 0.372125
[246]	valid_0's multi_logloss: 0.373266
[247]	valid_0's multi_logloss: 0.374384
[248]	valid_0's multi_logloss: 0.375603
[249]	valid_0's multi_logloss: 0.376556
[250]	valid_0's multi_logloss: 0.377572
[251]	valid_0's multi_logloss: 0.378696
[252]	valid_0's multi_logloss: 0.377298
[253]	valid_0's multi_logloss: 0.374965
[254]	valid_0's multi_logloss: 0.37615
[255]	valid_0's multi_logloss: 0.372715
[256]	valid_0's multi_logloss: 0.370285
[257]	valid_0's multi_logloss: 0.36706
[258]	valid_0's multi_logloss: 0.368409
[259]	valid_0's multi_logloss: 0.369343
[260]	valid_0's multi_logloss: 0.366968
[261]	valid_0's multi_logloss: 0.367782
[262]	valid_0's multi_logloss: 0.365771
[263]	valid_0's multi_logloss: 0.366661
[264]	valid_0's multi_logloss: 0.367875
[265]	valid_0's multi_logloss: 0.368822
[266]	valid_0's multi_logloss: 0.367691
[267]	valid_0's multi_logloss: 0.366293
[268]	valid_0's multi_logloss: 0.367343
[269]	valid_0's multi_logloss: 0.365366
[270]	valid_0's multi_logloss: 0.366105
[271]	valid_0's multi_logloss: 0.366964
[272]	valid_0's multi_logloss: 0.365104
[273]	valid_0's multi_logloss: 0.366103
[274]	valid_0's multi_logloss: 0.367071
[275]	valid_0's multi_logloss: 0.366123
[276]	valid_0's multi_logloss: 0.363652
[277]	valid_0's multi_logloss: 0.361142
[278]	valid_0's multi_logloss: 0.361945
[279]	valid_0's multi_logloss: 0.358942
[280]	valid_0's multi_logloss: 0.356394
[281]	valid_0's multi_logloss: 0.357229
[282]	valid_0's multi_logloss: 0.358192
[283]	valid_0's multi_logloss: 0.359124
[284]	valid_0's multi_logloss: 0.360069
[285]	valid_0's multi_logloss: 0.357011
[286]	valid_0's multi_logloss: 0.357835
[287]	valid_0's multi_logloss: 0.35571
[288]	valid_0's multi_logloss: 0.35431
[289]	valid_0's multi_logloss: 0.35521
[290]	valid_0's multi_logloss: 0.355934
[291]	valid_0's multi_logloss: 0.353708
[292]	valid_0's multi_logloss: 0.352507
[293]	valid_0's multi_logloss: 0.35142
[294]	valid_0's multi_logloss: 0.349045
[295]	valid_0's multi_logloss: 0.34768
[296]	valid_0's multi_logloss: 0.348647
[297]	valid_0's multi_logloss: 0.347517
[298]	valid_0's multi_logloss: 0.346804
[299]	valid_0's multi_logloss: 0.347399
[300]	valid_0's multi_logloss: 0.345322
[301]	valid_0's multi_logloss: 0.345982
[302]	valid_0's multi_logloss: 0.346773
[303]	valid_0's multi_logloss: 0.345948
[304]	valid_0's multi_logloss: 0.346614
[305]	valid_0's multi_logloss: 0.347424
[306]	valid_0's multi_logloss: 0.348128
[307]	valid_0's multi_logloss: 0.348791
[308]	valid_0's multi_logloss: 0.347148
[309]	valid_0's multi_logloss: 0.344977
[310]	valid_0's multi_logloss: 0.34314
[311]	valid_0's multi_logloss: 0.342278
[312]	valid_0's multi_logloss: 0.343137
[313]	valid_0's multi_logloss: 0.343886
[314]	valid_0's multi_logloss: 0.344552
[315]	valid_0's multi_logloss: 0.342027
[316]	valid_0's multi_logloss: 0.340547
[317]	valid_0's multi_logloss: 0.341149
[318]	valid_0's multi_logloss: 0.341854
[319]	valid_0's multi_logloss: 0.341192
[320]	valid_0's multi_logloss: 0.339611
[321]	valid_0's multi_logloss: 0.338406
[322]	valid_0's multi_logloss: 0.338329
[323]	valid_0's multi_logloss: 0.337364
[324]	valid_0's multi_logloss: 0.335823
[325]	valid_0's multi_logloss: 0.333051
[326]	valid_0's multi_logloss: 0.33383
[327]	valid_0's multi_logloss: 0.334565
[328]	valid_0's multi_logloss: 0.332835
[329]	valid_0's multi_logloss: 0.330619
[330]	valid_0's multi_logloss: 0.331298
[331]	valid_0's multi_logloss: 0.331849
[332]	valid_0's multi_logloss: 0.332501
[333]	valid_0's multi_logloss: 0.333226
[334]	valid_0's multi_logloss: 0.331168
[335]	valid_0's multi_logloss: 0.330751
[336]	valid_0's multi_logloss: 0.330299
[337]	valid_0's multi_logloss: 0.330893
[338]	valid_0's multi_logloss: 0.331461
[339]	valid_0's multi_logloss: 0.32983
[340]	valid_0's multi_logloss: 0.330414
[341]	valid_0's multi_logloss: 0.331061
[342]	valid_0's multi_logloss: 0.328683
[343]	valid_0's multi_logloss: 0.329306
[344]	valid_0's multi_logloss: 0.327192
[345]	valid_0's multi_logloss: 0.327764
[346]	valid_0's multi_logloss: 0.327122
[347]	valid_0's multi_logloss: 0.327718
[348]	valid_0's multi_logloss: 0.32707
[349]	valid_0's multi_logloss: 0.327589
[350]	valid_0's multi_logloss: 0.325887
Did not meet early stopping. Best iteration is:
[350]	valid_0's multi_logloss: 0.325887

C:\Users\micha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

###
[1]	valid_0's multi_logloss: 1.22235
Training until validation scores don't improve for 20 rounds.
[2]	valid_0's multi_logloss: 1.1142
[3]	valid_0's multi_logloss: 1.03777
[4]	valid_0's multi_logloss: 0.979913
[5]	valid_0's multi_logloss: 0.936654
[6]	valid_0's multi_logloss: 0.90016
[7]	valid_0's multi_logloss: 0.868653
[8]	valid_0's multi_logloss: 0.840221
[9]	valid_0's multi_logloss: 0.817237
[10]	valid_0's multi_logloss: 0.828758
[11]	valid_0's multi_logloss: 0.805716
[12]	valid_0's multi_logloss: 0.781423
[13]	valid_0's multi_logloss: 0.761967
[14]	valid_0's multi_logloss: 0.745529
[15]	valid_0's multi_logloss: 0.754379
[16]	valid_0's multi_logloss: 0.738754
[17]	valid_0's multi_logloss: 0.739006
[18]	valid_0's multi_logloss: 0.735739
[19]	valid_0's multi_logloss: 0.723312
[20]	valid_0's multi_logloss: 0.711792
[21]	valid_0's multi_logloss: 0.700984
[22]	valid_0's multi_logloss: 0.7021
[23]	valid_0's multi_logloss: 0.702074
[24]	valid_0's multi_logloss: 0.688675
[25]	valid_0's multi_logloss: 0.676714
[26]	valid_0's multi_logloss: 0.669
[27]	valid_0's multi_logloss: 0.671671
[28]	valid_0's multi_logloss: 0.679077
[29]	valid_0's multi_logloss: 0.665091
[30]	valid_0's multi_logloss: 0.653756
[31]	valid_0's multi_logloss: 0.657037
[32]	valid_0's multi_logloss: 0.646957
[33]	valid_0's multi_logloss: 0.63791
[34]	valid_0's multi_logloss: 0.628842
[35]	valid_0's multi_logloss: 0.631269
[36]	valid_0's multi_logloss: 0.633884
[37]	valid_0's multi_logloss: 0.641051
[38]	valid_0's multi_logloss: 0.644804
[39]	valid_0's multi_logloss: 0.632478
[40]	valid_0's multi_logloss: 0.635935
[41]	valid_0's multi_logloss: 0.640727
[42]	valid_0's multi_logloss: 0.644277
[43]	valid_0's multi_logloss: 0.645377
[44]	valid_0's multi_logloss: 0.65047
[45]	valid_0's multi_logloss: 0.636495
[46]	valid_0's multi_logloss: 0.639467
[47]	valid_0's multi_logloss: 0.643752
[48]	valid_0's multi_logloss: 0.645049
[49]	valid_0's multi_logloss: 0.649434
[50]	valid_0's multi_logloss: 0.653893
[51]	valid_0's multi_logloss: 0.643461
[52]	valid_0's multi_logloss: 0.630053
[53]	valid_0's multi_logloss: 0.631294
[54]	valid_0's multi_logloss: 0.622394
[55]	valid_0's multi_logloss: 0.624195
[56]	valid_0's multi_logloss: 0.62871
[57]	valid_0's multi_logloss: 0.62032
[58]	valid_0's multi_logloss: 0.624723
[59]	valid_0's multi_logloss: 0.613014
[60]	valid_0's multi_logloss: 0.614084
[61]	valid_0's multi_logloss: 0.618801
[62]	valid_0's multi_logloss: 0.609107
[63]	valid_0's multi_logloss: 0.599705
[64]	valid_0's multi_logloss: 0.591705
[65]	valid_0's multi_logloss: 0.581097
[66]	valid_0's multi_logloss: 0.574998
[67]	valid_0's multi_logloss: 0.575963
[68]	valid_0's multi_logloss: 0.576314
[69]	valid_0's multi_logloss: 0.567521
[70]	valid_0's multi_logloss: 0.569987
[71]	valid_0's multi_logloss: 0.561671
[72]	valid_0's multi_logloss: 0.556085
[73]	valid_0's multi_logloss: 0.550058
[74]	valid_0's multi_logloss: 0.553735
[75]	valid_0's multi_logloss: 0.557906
[76]	valid_0's multi_logloss: 0.551619
[77]	valid_0's multi_logloss: 0.553993
[78]	valid_0's multi_logloss: 0.548707
[79]	valid_0's multi_logloss: 0.550667
[80]	valid_0's multi_logloss: 0.553332
[81]	valid_0's multi_logloss: 0.545164
[82]	valid_0's multi_logloss: 0.538892
[83]	valid_0's multi_logloss: 0.541071
[84]	valid_0's multi_logloss: 0.535446
[85]	valid_0's multi_logloss: 0.536661
[86]	valid_0's multi_logloss: 0.539964
[87]	valid_0's multi_logloss: 0.533291
[88]	valid_0's multi_logloss: 0.535789
[89]	valid_0's multi_logloss: 0.52918
[90]	valid_0's multi_logloss: 0.521584
[91]	valid_0's multi_logloss: 0.517059
[92]	valid_0's multi_logloss: 0.519572
[93]	valid_0's multi_logloss: 0.521607
[94]	valid_0's multi_logloss: 0.52493
[95]	valid_0's multi_logloss: 0.527381
[96]	valid_0's multi_logloss: 0.519401
[97]	valid_0's multi_logloss: 0.515809
[98]	valid_0's multi_logloss: 0.508688
[99]	valid_0's multi_logloss: 0.511574
[100]	valid_0's multi_logloss: 0.507704
[101]	valid_0's multi_logloss: 0.508972
[102]	valid_0's multi_logloss: 0.511386
[103]	valid_0's multi_logloss: 0.505739
[104]	valid_0's multi_logloss: 0.508198
[105]	valid_0's multi_logloss: 0.500981
[106]	valid_0's multi_logloss: 0.495136
[107]	valid_0's multi_logloss: 0.490364
[108]	valid_0's multi_logloss: 0.492827
[109]	valid_0's multi_logloss: 0.494629
[110]	valid_0's multi_logloss: 0.497364
[111]	valid_0's multi_logloss: 0.491536
[112]	valid_0's multi_logloss: 0.484258
[113]	valid_0's multi_logloss: 0.479826
[114]	valid_0's multi_logloss: 0.481332
[115]	valid_0's multi_logloss: 0.477142
[116]	valid_0's multi_logloss: 0.479388
[117]	valid_0's multi_logloss: 0.48174
[118]	valid_0's multi_logloss: 0.484611
[119]	valid_0's multi_logloss: 0.478653
[120]	valid_0's multi_logloss: 0.480944
[121]	valid_0's multi_logloss: 0.476291
[122]	valid_0's multi_logloss: 0.47157
[123]	valid_0's multi_logloss: 0.467665
[124]	valid_0's multi_logloss: 0.463036
[125]	valid_0's multi_logloss: 0.465477
[126]	valid_0's multi_logloss: 0.4674
[127]	valid_0's multi_logloss: 0.462121
[128]	valid_0's multi_logloss: 0.458779
[129]	valid_0's multi_logloss: 0.45533
[130]	valid_0's multi_logloss: 0.451631
[131]	valid_0's multi_logloss: 0.447174
[132]	valid_0's multi_logloss: 0.448452
[133]	valid_0's multi_logloss: 0.445387
[134]	valid_0's multi_logloss: 0.44013
[135]	valid_0's multi_logloss: 0.440199
[136]	valid_0's multi_logloss: 0.436602
[137]	valid_0's multi_logloss: 0.433959
[138]	valid_0's multi_logloss: 0.432297
[139]	valid_0's multi_logloss: 0.434015
[140]	valid_0's multi_logloss: 0.43591
[141]	valid_0's multi_logloss: 0.430709
[142]	valid_0's multi_logloss: 0.432335
[143]	valid_0's multi_logloss: 0.427941
[144]	valid_0's multi_logloss: 0.429625
[145]	valid_0's multi_logloss: 0.431292
[146]	valid_0's multi_logloss: 0.427045
[147]	valid_0's multi_logloss: 0.423815
[148]	valid_0's multi_logloss: 0.420904
[149]	valid_0's multi_logloss: 0.421926
[150]	valid_0's multi_logloss: 0.423642
[151]	valid_0's multi_logloss: 0.425356
[152]	valid_0's multi_logloss: 0.420178
[153]	valid_0's multi_logloss: 0.421709
[154]	valid_0's multi_logloss: 0.416742
[155]	valid_0's multi_logloss: 0.414226
[156]	valid_0's multi_logloss: 0.410512
[157]	valid_0's multi_logloss: 0.412207
[158]	valid_0's multi_logloss: 0.409364
[159]	valid_0's multi_logloss: 0.406152
[160]	valid_0's multi_logloss: 0.400564
[161]	valid_0's multi_logloss: 0.402265
[162]	valid_0's multi_logloss: 0.399148
[163]	valid_0's multi_logloss: 0.396574
[164]	valid_0's multi_logloss: 0.393088
[165]	valid_0's multi_logloss: 0.394296
[166]	valid_0's multi_logloss: 0.390881
[167]	valid_0's multi_logloss: 0.392371
[168]	valid_0's multi_logloss: 0.39425
[169]	valid_0's multi_logloss: 0.395632
[170]	valid_0's multi_logloss: 0.397086
[171]	valid_0's multi_logloss: 0.398575
[172]	valid_0's multi_logloss: 0.394605
[173]	valid_0's multi_logloss: 0.396066
[174]	valid_0's multi_logloss: 0.392614
[175]	valid_0's multi_logloss: 0.388547
[176]	valid_0's multi_logloss: 0.38486
[177]	valid_0's multi_logloss: 0.380996
[178]	valid_0's multi_logloss: 0.377794
[179]	valid_0's multi_logloss: 0.379309
[180]	valid_0's multi_logloss: 0.380699
[181]	valid_0's multi_logloss: 0.37686
[182]	valid_0's multi_logloss: 0.378438
[183]	valid_0's multi_logloss: 0.379747
[184]	valid_0's multi_logloss: 0.377454
[185]	valid_0's multi_logloss: 0.379114
[186]	valid_0's multi_logloss: 0.38075
[187]	valid_0's multi_logloss: 0.382153
[188]	valid_0's multi_logloss: 0.378611
[189]	valid_0's multi_logloss: 0.375474
[190]	valid_0's multi_logloss: 0.37164
[191]	valid_0's multi_logloss: 0.369648
[192]	valid_0's multi_logloss: 0.371151
[193]	valid_0's multi_logloss: 0.367438
[194]	valid_0's multi_logloss: 0.368852
[195]	valid_0's multi_logloss: 0.369962
[196]	valid_0's multi_logloss: 0.371288
[197]	valid_0's multi_logloss: 0.372854
[198]	valid_0's multi_logloss: 0.374215
[199]	valid_0's multi_logloss: 0.375702
[200]	valid_0's multi_logloss: 0.376695
[201]	valid_0's multi_logloss: 0.37312
[202]	valid_0's multi_logloss: 0.370887
[203]	valid_0's multi_logloss: 0.372609
[204]	valid_0's multi_logloss: 0.370254
[205]	valid_0's multi_logloss: 0.367282
[206]	valid_0's multi_logloss: 0.368396
[207]	valid_0's multi_logloss: 0.369712
[208]	valid_0's multi_logloss: 0.367415
[209]	valid_0's multi_logloss: 0.368472

[210]	valid_0's multi_logloss: 0.369596
[211]	valid_0's multi_logloss: 0.366209
[212]	valid_0's multi_logloss: 0.36766
[213]	valid_0's multi_logloss: 0.368895
[214]	valid_0's multi_logloss: 0.369835
[215]	valid_0's multi_logloss: 0.370926
[216]	valid_0's multi_logloss: 0.372078
[217]	valid_0's multi_logloss: 0.369902
[218]	valid_0's multi_logloss: 0.368492
[219]	valid_0's multi_logloss: 0.369678
[220]	valid_0's multi_logloss: 0.370988
[221]	valid_0's multi_logloss: 0.372333
[222]	valid_0's multi_logloss: 0.370829
[223]	valid_0's multi_logloss: 0.37197
[224]	valid_0's multi_logloss: 0.373059
[225]	valid_0's multi_logloss: 0.369173
[226]	valid_0's multi_logloss: 0.36689
[227]	valid_0's multi_logloss: 0.368318
[228]	valid_0's multi_logloss: 0.36954
[229]	valid_0's multi_logloss: 0.366935
[230]	valid_0's multi_logloss: 0.368032
[231]	valid_0's multi_logloss: 0.366478
Early stopping, best iteration is:
[211]	valid_0's multi_logloss: 0.366209

C:\Users\micha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

###
[1]	valid_0's multi_logloss: 1.23746
Training until validation scores don't improve for 20 rounds.
[2]	valid_0's multi_logloss: 1.14387
[3]	valid_0's multi_logloss: 1.06976
[4]	valid_0's multi_logloss: 1.01159
[5]	valid_0's multi_logloss: 0.965063
[6]	valid_0's multi_logloss: 0.930503
[7]	valid_0's multi_logloss: 0.899747
[8]	valid_0's multi_logloss: 0.873986
[9]	valid_0's multi_logloss: 0.850232
[10]	valid_0's multi_logloss: 0.858602
[11]	valid_0's multi_logloss: 0.837565
[12]	valid_0's multi_logloss: 0.821248
[13]	valid_0's multi_logloss: 0.805131
[14]	valid_0's multi_logloss: 0.789953
[15]	valid_0's multi_logloss: 0.79783
[16]	valid_0's multi_logloss: 0.782227
[17]	valid_0's multi_logloss: 0.781737
[18]	valid_0's multi_logloss: 0.780365
[19]	valid_0's multi_logloss: 0.760872
[20]	valid_0's multi_logloss: 0.749183
[21]	valid_0's multi_logloss: 0.734965
[22]	valid_0's multi_logloss: 0.735884
[23]	valid_0's multi_logloss: 0.738719
[24]	valid_0's multi_logloss: 0.727545
[25]	valid_0's multi_logloss: 0.713765
[26]	valid_0's multi_logloss: 0.702716
[27]	valid_0's multi_logloss: 0.703448
[28]	valid_0's multi_logloss: 0.708312
[29]	valid_0's multi_logloss: 0.697905
[30]	valid_0's multi_logloss: 0.685309
[31]	valid_0's multi_logloss: 0.687108
[32]	valid_0's multi_logloss: 0.676588
[33]	valid_0's multi_logloss: 0.665144
[34]	valid_0's multi_logloss: 0.655394
[35]	valid_0's multi_logloss: 0.658651
[36]	valid_0's multi_logloss: 0.661721
[37]	valid_0's multi_logloss: 0.667574
[38]	valid_0's multi_logloss: 0.670746
[39]	valid_0's multi_logloss: 0.661035
[40]	valid_0's multi_logloss: 0.664528
[41]	valid_0's multi_logloss: 0.669098
[42]	valid_0's multi_logloss: 0.672294
[43]	valid_0's multi_logloss: 0.673986
[44]	valid_0's multi_logloss: 0.678223
[45]	valid_0's multi_logloss: 0.66778
[46]	valid_0's multi_logloss: 0.670174
[47]	valid_0's multi_logloss: 0.673705
[48]	valid_0's multi_logloss: 0.6757
[49]	valid_0's multi_logloss: 0.679692
[50]	valid_0's multi_logloss: 0.683088
[51]	valid_0's multi_logloss: 0.672621
[52]	valid_0's multi_logloss: 0.662653
[53]	valid_0's multi_logloss: 0.665045
[54]	valid_0's multi_logloss: 0.655736
Early stopping, best iteration is:
[34]	valid_0's multi_logloss: 0.655394

C:\Users\micha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

###
[1]	valid_0's multi_logloss: 1.2209
Training until validation scores don't improve for 20 rounds.
[2]	valid_0's multi_logloss: 1.11477
[3]	valid_0's multi_logloss: 1.03829
[4]	valid_0's multi_logloss: 0.981435
[5]	valid_0's multi_logloss: 0.935038
[6]	valid_0's multi_logloss: 0.899263
[7]	valid_0's multi_logloss: 0.868395
[8]	valid_0's multi_logloss: 0.839667
[9]	valid_0's multi_logloss: 0.814962
[10]	valid_0's multi_logloss: 0.825803
[11]	valid_0's multi_logloss: 0.806547
[12]	valid_0's multi_logloss: 0.788471
[13]	valid_0's multi_logloss: 0.771405
[14]	valid_0's multi_logloss: 0.755845
[15]	valid_0's multi_logloss: 0.762639
[16]	valid_0's multi_logloss: 0.744756
[17]	valid_0's multi_logloss: 0.745428
[18]	valid_0's multi_logloss: 0.743335
[19]	valid_0's multi_logloss: 0.728917
[20]	valid_0's multi_logloss: 0.712009
[21]	valid_0's multi_logloss: 0.701305
[22]	valid_0's multi_logloss: 0.70382
[23]	valid_0's multi_logloss: 0.705377
[24]	valid_0's multi_logloss: 0.695065
[25]	valid_0's multi_logloss: 0.683508
[26]	valid_0's multi_logloss: 0.676213
[27]	valid_0's multi_logloss: 0.678144
[28]	valid_0's multi_logloss: 0.684194
[29]	valid_0's multi_logloss: 0.670636
[30]	valid_0's multi_logloss: 0.659427
[31]	valid_0's multi_logloss: 0.660102
[32]	valid_0's multi_logloss: 0.650282
[33]	valid_0's multi_logloss: 0.639347
[34]	valid_0's multi_logloss: 0.629266
[35]	valid_0's multi_logloss: 0.632094
[36]	valid_0's multi_logloss: 0.634173
[37]	valid_0's multi_logloss: 0.640278
[38]	valid_0's multi_logloss: 0.644294
[39]	valid_0's multi_logloss: 0.633856
[40]	valid_0's multi_logloss: 0.638005
[41]	valid_0's multi_logloss: 0.642328
[42]	valid_0's multi_logloss: 0.645005
[43]	valid_0's multi_logloss: 0.647052
[44]	valid_0's multi_logloss: 0.651934
[45]	valid_0's multi_logloss: 0.642336
[46]	valid_0's multi_logloss: 0.644232
[47]	valid_0's multi_logloss: 0.647667
[48]	valid_0's multi_logloss: 0.648868
[49]	valid_0's multi_logloss: 0.653044
[50]	valid_0's multi_logloss: 0.657158
[51]	valid_0's multi_logloss: 0.649122
[52]	valid_0's multi_logloss: 0.639731
[53]	valid_0's multi_logloss: 0.641871
[54]	valid_0's multi_logloss: 0.631276
Early stopping, best iteration is:
[34]	valid_0's multi_logloss: 0.629266

C:\Users\micha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

###
[1]	valid_0's multi_logloss: 1.23687
Training until validation scores don't improve for 20 rounds.
[2]	valid_0's multi_logloss: 1.13528
[3]	valid_0's multi_logloss: 1.0631
[4]	valid_0's multi_logloss: 1.0078
[5]	valid_0's multi_logloss: 0.964162
[6]	valid_0's multi_logloss: 0.927906
[7]	valid_0's multi_logloss: 0.896156
[8]	valid_0's multi_logloss: 0.868872
[9]	valid_0's multi_logloss: 0.843874
[10]	valid_0's multi_logloss: 0.855088
[11]	valid_0's multi_logloss: 0.833319
[12]	valid_0's multi_logloss: 0.813393
[13]	valid_0's multi_logloss: 0.795416
[14]	valid_0's multi_logloss: 0.777572
[15]	valid_0's multi_logloss: 0.785707
[16]	valid_0's multi_logloss: 0.770642
[17]	valid_0's multi_logloss: 0.772055
[18]	valid_0's multi_logloss: 0.769812
[19]	valid_0's multi_logloss: 0.757356
[20]	valid_0's multi_logloss: 0.742142
[21]	valid_0's multi_logloss: 0.727247
[22]	valid_0's multi_logloss: 0.728632
[23]	valid_0's multi_logloss: 0.728519
[24]	valid_0's multi_logloss: 0.718728
[25]	valid_0's multi_logloss: 0.705457
[26]	valid_0's multi_logloss: 0.694715
[27]	valid_0's multi_logloss: 0.696221
[28]	valid_0's multi_logloss: 0.70094
[29]	valid_0's multi_logloss: 0.688417
[30]	valid_0's multi_logloss: 0.67919
[31]	valid_0's multi_logloss: 0.682194
[32]	valid_0's multi_logloss: 0.671166
[33]	valid_0's multi_logloss: 0.662947
[34]	valid_0's multi_logloss: 0.650484
[35]	valid_0's multi_logloss: 0.65352
[36]	valid_0's multi_logloss: 0.655584
[37]	valid_0's multi_logloss: 0.662008
[38]	valid_0's multi_logloss: 0.665447
[39]	valid_0's multi_logloss: 0.655258
[40]	valid_0's multi_logloss: 0.659599
[41]	valid_0's multi_logloss: 0.663746
[42]	valid_0's multi_logloss: 0.667452
[43]	valid_0's multi_logloss: 0.668898
[44]	valid_0's multi_logloss: 0.673636
[45]	valid_0's multi_logloss: 0.665141
[46]	valid_0's multi_logloss: 0.666916
[47]	valid_0's multi_logloss: 0.670829
[48]	valid_0's multi_logloss: 0.672028
[49]	valid_0's multi_logloss: 0.67629
[50]	valid_0's multi_logloss: 0.680573
[51]	valid_0's multi_logloss: 0.671242
[52]	valid_0's multi_logloss: 0.662178
[53]	valid_0's multi_logloss: 0.663603
[54]	valid_0's multi_logloss: 0.653458
Early stopping, best iteration is:
[34]	valid_0's multi_logloss: 0.650484

C:\Users\micha\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [52]:
#sorted(zip(model.feature_importances_, train.columns), reverse=True)

In [180]:
submission = pd.DataFrame(np.array(predicts).mean(axis=0).round().astype(int),
                             columns=['Target'],
                             index=test_set.index)

In [182]:
submission.reset_index(inplace=True)

In [183]:
submission.head()

             Id  Target
0  ID_2f6873615       3
1  ID_1c78846d2       3
2  ID_e5442cf6a       3
3             0       3
4  ID_a62966799       2

In [ ]:
submission.to_csv('submission.csv', index=False)